spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blublog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true   #在控制台中打印sql
      
logging:
  level: 
    root: info
    com.blu: debug
  file: log/blog-dev.log
  